[platformio]
src_dir = JellyfishForest

[env:esp32dev]
platform = espressif32@6.8.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  makuna/NeoPixelBus@2.8.2
  bogde/HX711
  bblanchon/ArduinoJson@^6.21.5
